In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

In [22]:
data = pd.read_csv("Litracy.csv")
data.head(10)

,District,Zone,Geographical Region,Development Region,Sub Group,Male /Female,Value
0,Taplejung,Mechi,Mountain,Eastern,Literate Population by age 15 - 24,Male,11483
1,Taplejung,Mechi,Mountain,Eastern,Literate Population by age 15 - 24,Female,13133
2,Taplejung,Mechi,Mountain,Eastern,Total Population by age 15 - 24,Male,12116
3,Taplejung,Mechi,Mountain,Eastern,Total Population by age 15 - 24,Female,14176
4,Panchthar,Mechi,Hill,Eastern,Literate Population by age 15 - 24,Male,17228
5,Panchthar,Mechi,Hill,Eastern,Literate Population by age 15 - 24,Female,21424
6,Panchthar,Mechi,Hill,Eastern,Total Population by age 15 - 24,Male,17877
7,Panchthar,Mechi,Hill,Eastern,Total Population by age 15 - 24,Female,22519
8,Ilam,Mechi,Hill,Eastern,Literate Population by age 15 - 24,Male,27645
9,Ilam,Mechi,Hill,Eastern,Literate Population by age 15 - 24,Female,32077

In [23]:
import statsmodels.api as sm
from scipy import stats

In [ ]:
data['Value'].hist()

In [24]:
sum_of_all=data['Value'].sum()

In [25]:
data["Percent"] = (data['Value']*100)/sum_of_all

In [27]:
data["Percent"] = data['Percent']*100

In [28]:
data['Percent']

0      11.751390
1      13.439955
2      12.399185
3      14.507333
4      17.630667
         ...
295    27.197156
296    10.400538
297    11.256078
298    10.859009
299    14.077516
Name: Percent, Length: 300, dtype: float64

In [34]:
mean_data = data['Percent'].mean()

In [31]:
data['Value'].std()

30100.40076821091

In [35]:
std_data = data['Percent'].std()

In [37]:
upper_limit = mean_data + 1*std_data
lower_limit = mean_data - 1*std_data
((data['Percent'] >= lower_limit) & (data['Percent'] <= upper_limit)).mean()

0.8533333333333334

In [ ]:
## Data is not Normally Distributed

In [39]:
upper_limit = mean_data + 3*std_data
lower_limit = mean_data - 3*std_data
((data['Percent'] >= lower_limit) & (data['Percent'] <= upper_limit)).mean()

0.9866666666666667

In [40]:
data['Z-Score'] = stats.zscore(data['Percent'])

In [43]:
data[(data['Z-Score'] < -3) | (data['Z-Score'] > 3)]

,District,Zone,Geographical Region,Development Region,Sub Group,Male /Female,Value,Percent,Z-Score
104,Kathmandu,Bagmati,Hill,Central,Literate Population by age 15 - 24,Male,224913,230.169849,6.400657
105,Kathmandu,Bagmati,Hill,Central,Literate Population by age 15 - 24,Female,192055,196.543865,5.307220
106,Kathmandu,Bagmati,Hill,Central,Total Population by age 15 - 24,Male,232870,238.312827,6.665447
107,Kathmandu,Bagmati,Hill,Central,Total Population by age 15 - 24,Female,203098,207.844971,5.674705

In [44]:
 ## Random Sampling for Data

In [45]:
random_sample = data.sample(n=50, replace=True,random_state=31208)
random_sample

,District,Zone,Geographical Region,Development Region,Sub Group,Male /Female,Value,Percent,Z-Score
103,Bhaktapur,Bagmati,Hill,Central,Total Population by age 15 - 24,Female,34167,34.965579,0.053077
210,Rolpa,Rapti,Hill,Mid-Western,Total Population by age 15 - 24,Male,17558,17.968380,-0.499632
181,Gulmi,Lumbini,Hill,Western,Literate Population by age 15 - 24,Female,31256,31.986541,-0.043795
248,Jumla,Karnali,Mountain,Mid-Western,Literate Population by age 15 - 24,Male,8755,8.959629,-0.792575
276,Doti,Seti,Hill,Far-Western,Literate Population by age 15 - 24,Male,15156,15.510238,-0.579565
252,Kalikot,Karnali,Mountain,Mid-Western,Literate Population by age 15 - 24,Male,10735,10.985907,-0.726685
10,Ilam,Mechi,Hill,Eastern,Total Population by age 15 - 24,Male,28524,29.190686,-0.134709
126,Rautahat,Narayani,Terai,Central,Total Population by age 15 - 24,Male,59294,60.679867,0.889244
142,Gorkha,Gandaki,Hill,Western,Total Population by age 15 - 24,Male,20654,21.136742,-0.396604
221,Dang,Rapti,Terai,Mid-Western,Literate Population by age 15 - 24,Female,56758,58.084594,0.804852
84,Dolakha,Janakpur,Mountain,Central,Literate Population by age 15 - 24,Male,15062,15.414041,-0.582693
254,Kalikot,Karnali,Mountain,Mid-Western,Total Population by age 15 - 24,Male,12076,12.358250,-0.682060
271,Bajhang,Seti,Mountain,Far-Western,Total Population by age 15 - 24,Female,18399,18.829036,-0.471645
256,Mugu,Karnali,Mountain,Mid-Western,Literate Population by age 15 - 24,Male,4049,4.143637,-0.949180
247,Dolpa,Karnali,Mountain,Mid-Western,Total Population by age 15 - 24,Female,3459,3.539847,-0.968814
239,Dailekh,Bheri,Hill,Mid-Western,Total Population by age 15 - 24,Female,27273,27.910447,-0.176339
291,Dadeldhura,Mahakali,Hill,Far-Western,Total Population by age 15 - 24,Female,15536,15.899120,-0.566919
177,Baglung,Dhawalagiri,Hill,Western,Literate Population by age 15 - 24,Female,29816,30.512884,-0.091714
163,Manang,Gandaki,Mountain,Western,Total Population by age 15 - 24,Female,514,0.526014,-1.066816
274,Achham,Seti,Hill,Far-Western,Total Population by age 15 - 24,Male,20664,21.146976,-0.396271
12,Jhapa,Mechi,Terai,Eastern,Literate Population by age 15 - 24,Male,67750,69.333508,1.170640
262,Humla,Karnali,Mountain,Mid-Western,Total Population by age 15 - 24,Male,4298,4.398456,-0.940894
36,Bhojpur,Kosi,Hill,Eastern,Literate Population by age 15 - 24,Male,15475,15.836694,-0.568949
126,Rautahat,Narayani,Terai,Central,Total Population by age 15 - 24,Male,59294,60.679867,0.889244
191,Nawalparasi,Lumbini,Terai,Western,Total Population by age 15 - 24,Female,73336,75.050069,1.356529
184,Palpa,Lumbini,Hill,Western,Literate Population by age 15 - 24,Male,21518,22.020936,-0.367852
157,Kaski,Gandaki,Hill,Western,Literate Population by age 15 - 24,Female,55122,56.410356,0.750410
109,Nuwakot,Bagmati,Hill,Central,Literate Population by age 15 - 24,Female,25661,26.260770,-0.229983
292,Baitadi,Mahakali,Hill,Far-Western,Literate Population by age 15 - 24,Male,19443,19.897438,-0.436903
207,Pyuthan,Rapti,Hill,Mid-Western,Total Population by age 15 - 24,Female,25825,26.428603,-0.224525
95,Kavre,Bagmati,Hill,Central,Total Population by age 15 - 24,Female,43855,44.880015,0.375471
76,Sindhuli,Janakpur,Hill,Central,Literate Population by age 15 - 24,Male,22606,23.134366,-0.331646
182,Gulmi,Lumbini,Hill,Western,Total Population by age 15 - 24,Male,19778,20.240267,-0.425755
145,Lamjung,Gandaki,Hill,Western,Literate Population by age 15 - 24,Female,16529,16.915329,-0.533875
103,Bhaktapur,Bagmati,Hill,Central,Total Population by age 15 - 24,Female,34167,34.965579,0.053077
248,Jumla,Karnali,Mountain,Mid-Western,Literate Population by age 15 - 24,Male,8755,8.959629,-0.792575
107,Kathmandu,Bagmati,Hill,Central,Total Population by age 15 - 24,Female,203098,207.844971,5.674705
54,Udayapur,Sagarmatha,Hill,Eastern,Total Population by age 15 - 24,Male,27785,28.434414,-0.159301
53,Udayapur,Sagarmatha,Hill,Eastern,Literate Population by age 15 - 24,Female,32273,33.027311,-0.009951
79,Sindhuli,Janakpur,Hill,Central,Total Population by age 15 - 24,Female,31724,32.465479,-0.028221
243,Jajarkot,Bheri,Hill,Mid-Western,Total Population by age 15 - 24,Female,16555,16.941937,-0.533009
83,Ramechhap,Janakpur,Hill,Central,Total Population by age 15 - 24,Female,22963,23.499710,-0.319766
92,Kavre,Bagmati,Hill,Central,Literate Population by age 15 - 24,Male,35397,36.224327,0.094008
68,Mahottari,Janakpur,Terai,Central,Literate Population by age 15 - 24,Male,36146,36.990834,0.118933
161,Manang,Gandaki,Mountain,Western,Literate Population by age 15 - 24,Female,481,0.492242,-1.067914
118,Dhading,Bagmati,Hill,Central,Total Population by age 15 - 24,Male,28200,28.859113,-0.145491
49,Khotang,Sagarmatha,Hill,Eastern,Literate Population by age 15 - 24,Female,20846,21.333230,-0.390215
130,Bara,Narayani,Terai,Central,Total Population by age 15 - 24,Male,61979,63.427623,0.978595
24,Dhankuta,Kosi,Hill,Eastern,Literate Population by age 15 - 24,Male,14624,14.965804,-0.597269
60,Siraha,Sagarmatha,Terai,Eastern,Literate Population by age 15 - 24,Male,40277,41.218387,0.256403

In [57]:
random_sample_mean = random_sample['Percent'].mean()
random_sample_mean
# mean_data

31.017713559996764

In [60]:
random_sample_mean_2 = data["Percent"].sample(n=50, replace=True,random_state=56810).mean()
random_sample_mean_2

28.888770632475097

In [61]:
random_sample_mean_3 = data["Percent"].sample(n=50, replace=True,random_state=78560).mean()
random_sample_mean_3

35.01967434230388

In [62]:
mean_data

33.333333333333336